config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :sessions, only: [:new, :create, :destroy]
  resources :professions
  get 'encyclopedia' => 'encyclopedia#index'

  get 'index' => "home#index"

  get 'about_us' => "home#about_us"

  resources :feedbacks

  get 'partners' => "home#partners"

  root "home#index"

  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"

  resources :users

  resources :attempts
  resources :surveys
  get '/survey/:id' => 'attempts#new'
  get '/choose_survey' => 'attempts#choose_survey'

  get '/stastistics' => 'attempt_statistic#index'

  

end

app/models/accountability.rb
class Accountability < ActiveRecord::Base
	belongs_to :profession
end

app/models/attainment.rb
class Attainment < ActiveRecord::Base
	has_and_belongs_to_many :competences
end

app/models/choice.rb
class Choice < ActiveRecord::Base
	belongs_to :question

	has_attached_file :choice_image
end

app/models/competence.rb
class Competence < ActiveRecord::Base
	has_many :tasks
	has_many :professions, :through => :tasks
	has_and_belongs_to_many :attainments
	has_and_belongs_to_many :skills
	has_and_belongs_to_many :knowledges
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
	has_many :knowledges
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	validates :name, :email, :content, presence: true  
	validates :email, format: { with: /\A[0-9a-zA-Z]+[@]+[a-zA-Z]+[.]+[a-zA-Z]+\z/, message: "@" }
	
end

app/models/knowledge.rb
class Knowledge < ActiveRecord::Base
	belongs_to :discipline
	has_and_belongs_to_many :competences
end

app/models/profession.rb
class Profession < ActiveRecord::Base
  has_one :qualification, dependent: :destroy
  has_one :accountability, dependent: :destroy
  has_one :responsibility, dependent: :destroy
  has_many :tasks
  has_many :competences, :through => :tasks
end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
	belongs_to :profession
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :test
  has_many :choices, dependent: :destroy

  has_attached_file :question_image
end

app/models/responsibility.rb
class Responsibility < ActiveRecord::Base
	belongs_to :profession
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	has_and_belongs_to_many :competences
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :profession
  belongs_to :competence
end

app/models/test.rb
class Test < ActiveRecord::Base
	has_many :test_session
	has_many :questions
end

app/models/test_session.rb
class TestSession < ActiveRecord::Base
  belongs_to :user
  belongs_to :test
  has_many :user_answers
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :login, :password, :password_confirmation, :email, presence: true  
  validates :email, format: { with: /\A[0-9a-zA-Z]+[@]+[a-zA-Z]+[.]+[a-zA-Z]+\z/, message: "@" }
  validates :password, confirmation: true

  belongs_to :profession


  has_secure_password
  
  has_surveys
  # attr_accessible :name, :login, :password, :password_confirmation, :email 
end

app/models/user_answer.rb
class UserAnswer < ActiveRecord::Base
  belongs_to :question
  belongs_to :choice
  belongs_to :test_session
end

app/controllers/professions_controller.rb
class ProfessionsController < ApplicationController
  skip_before_action :admin_login
  before_action :set_profession, only: [:show, :edit, :update, :destroy]

  # GET /professions
  # GET /professions.json
  def index
    @professions = Profession.all
  end

  # GET /professions/1
  # GET /professions/1.json
  def show
  end

  # GET /professions/new
  def new
    @profession = Profession.new
  end

  # GET /professions/1/edit
  def edit
  end

  # POST /professions
  # POST /professions.json
  def create
    @profession = Profession.new(profession_params)

    respond_to do |format|
      if @profession.save
        format.html { redirect_to @profession, notice: 'Profession was successfully created.' }
        format.json { render :show, status: :created, location: @profession }
      else
        format.html { render :new }
        format.json { render json: @profession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professions/1
  # PATCH/PUT /professions/1.json
  def update
    respond_to do |format|
      if @profession.update(profession_params)
        format.html { redirect_to @profession, notice: 'Profession was successfully updated.' }
        format.json { render :show, status: :ok, location: @profession }
      else
        format.html { render :edit }
        format.json { render json: @profession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professions/1
  # DELETE /professions/1.json
  def destroy
    @profession.destroy
    respond_to do |format|
      format.html { redirect_to professions_url, notice: 'Profession was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profession
      @profession = Profession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profession_params
      params.require(:profession).permit(:min_level_of_compet_test, :profession_name, :qualification_name_id, :level)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def link_to_remove_field(name, f)
    f.hidden_field(:_destroy) +
    __link_to_function(raw(name), "removeField(this)", :id =>"remove-attach")
  end

  def new_survey
    new_survey_path
  end

  def edit_survey(resource)
    edit_survey_path(resource)
  end

  def survey_scope(resource)
    if action_name =~ /new|create/
      surveys_path(resource)
    elsif action_name =~ /edit|update/
      survey_path(resource)
    end
  end

  def new_attempt
    new_attempt_path
  end

  def attempt_scope(resource)
    if action_name =~ /new|create/
     attempts_path(resource)
    elsif action_name =~ /edit|update/
      attempt_path(resource)
    end
  end

  def link_to_add_field(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object,:child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    __link_to_function(name, "addField(this, \"#{association}\", \"#{escape_javascript(fields)}\")",
    :id=>"add-attach",
    :class=>"btn btn-small btn-info")
  end

  private

  def __link_to_function(name, on_click_event, opts={})
    link_to(name, '#go_here', opts.merge(onclick: on_click_event))
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/professions/_form.html.haml
= form_for @profession do |f|
  - if @profession.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profession.errors.count, "error")} prohibited this profession from being saved:"
      %ul
        - @profession.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :min_level_of_compet_test
    = f.number_field :min_level_of_compet_test
  .field
    = f.label :profession_name
    = f.text_field :profession_name
  .field
    = f.label :qualification_name
    = f.text_field :qualification_name
  .field
    = f.label :level
    = f.number_field :level
  .actions
    = f.submit 'Save'

app/views/professions/edit.html.haml
%h1 Editing profession

= render 'form'

= link_to 'Show', @profession
\|
= link_to 'Back', professions_path

app/views/professions/index.html.haml
%h1 Listing professions

%table
  %thead
    %tr
      %th Min level of compet test
      %th Profession name
      %th Qualification name
      %th Level
      %th
      %th
      %th

  %tbody
    - @professions.each do |profession|
      %tr
        %td= profession.min_level_of_compet_test
        %td= profession.profession_name
        %td= profession.qualification_name
        %td= profession.level
        %td= link_to 'Show', profession
        %td= link_to 'Edit', edit_profession_path(profession)
        %td= link_to 'Destroy', profession, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profession', new_profession_path

app/views/professions/new.html.haml
%h1 New profession

= render 'form'

= link_to 'Back', professions_path

app/views/professions/show.html.haml
%p#notice= notice

%p
  %b Min level of compet test:
  = @profession.min_level_of_compet_test
%p
  %b Profession name:
  = @profession.profession_name
%p
  %b Qualification name:
  = @profession.qualification_name
%p
  %b Level:
  = @profession.level

= link_to 'Edit', edit_profession_path(@profession)
\|
= link_to 'Back', professions_path